# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fd6d96a562ecc0991948741448371422b407136bf900866c219b5dc3a6f53c18ea2f25cf313e8ea0d5d5a9b4c09de42779bb649973807ec366b51f19a1df7d36

test:
  secret_key_base: 2803e9104478f26b085bc0328c796d007503b0b727846e243b269acdf34899a00c36d5fdca08bbd7fdd447c6971f98a37847662d64cb8067d27f68906b7abc9d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
